# Generated by Django 4.1.3 on 2022-11-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('biografia', models.TextField(null=True)),
                ('libros', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('paginas', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('genero', models.CharField(choices=[('terror', 'terror'), ('romance', 'romance'), ('drama', 'drama'), ('comics', 'comics'), ('ficcion', 'ficcion'), ('infantil', 'infantil'), ('historia', 'historia'), ('juvenil', 'juvenil')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseña', models.TextField()),
                ('estrellas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
    ]
