# Generated by Django 4.1.3 on 2022-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='libro',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
